version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: C:\Users\circleci\project\TestApp\scripts\ImportCert.ps1 -KeyPath C:\Users\circleci\project\TestApp\TestApp_TemporaryKey.pfx -KeyPass testpassword
      - run: 
          name: build
          command: |
            $ProgressPreference = "SilentlyContinue"
            msbuild TestApp\TestApp.csproj /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64|ARM" /p:BuildAppxUploadPackageForUap=true /p:AppxPackageSigningEnabled=true  /p:PackageCertificatePassword="testpassword" -restore
      - run:
          name: Compress AppPackages
          command: Compress-Archive -Path ./TestApp/AppPackages -DestinationPath ./AppPackages.zip
      - store_artifacts:
          path: ./AppPackages.zip
workflows:
  version: 2
  build_and_upload_artifact:
    jobs:
      - build
